- hosts: webservers
  gather_facts: no

  tasks:
    - name: install cowsay
      ansible.builtin.apt:
        name: cowsay
        state: latest
      become: yes
      register: result
      tags: register_test

    - name: use cowsay
      ansible.builtin.command: cowsay "hi pidor"
      tags: register_test

    - name: show reg result
      ansible.builtin.debug:
        var: result
      tags: register_test

    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
      tags: nginx

    - name: install redis
      ansible.builtin.apt:
        name: redis-server
        state: present
        update_cache: yes
      become: yes
      tags: redis
