- hosts: webservers
  gather_facts: no

  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest
      become: yes
      tags: inst_git

    - name: check git version
      ansible.builtin.command: git version
      register: current_git_version
      tags: inst_git

    - debug:
        var: current_git_version.stdout_lines
      tags: inst_git

    - name: delete git
      ansible.builtin.apt:
        name: git
        state: absent
      become: yes

    - name: check git version
      ansible.builtin.command: git version
      register: new_git_version

    - debug:
        var: new_git_version
